name       : pycodestyle
version    : 2.7.0
release    : 10
source     :
    - https://github.com/PyCQA/pycodestyle/archive/refs/tags/2.7.0.tar.gz : 5651c4b981bb0620e6ffb6a94dd6a68ec7fdcbd88c3219e5a976424692700f56
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python3)
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
