name       : pycodestyle
version    : 2.9.1
release    : 13
source     :
    - https://github.com/PyCQA/pycodestyle/archive/refs/tags/2.9.1.tar.gz : d6d8182c2fe10f169192b1133cb11c008ca712da01ce41d8c14523f644c6fe05
homepage   : https://github.com/PyCQA/pycodestyle
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python3)
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
