name       : pycodestyle
version    : 2.3.1
release    : 2
source     :
    - https://github.com/PyCQA/pycodestyle/archive/2.3.1.tar.gz : e9fc1ca3fd85648f45c0d2e33591b608a17d8b9b78e22c5f898e831351bacb03
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
