name       : pycodestyle
version    : 2.3.1
release    : 1
source     :
    - https://pypi.python.org/packages/e1/88/0e2cbf412bd849ea6f1af1f97882add46a374f4ba1d2aea39353609150ad/pycodestyle-2.3.1.tar.gz : 682256a5b318149ca0d2a9185d365d8864a768a28db66a84a2ea946bcc426766
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
check:
    python setup.py test
