name       : pycodestyle
version    : 2.4.0
release    : 4
source     :
    - https://github.com/PyCQA/pycodestyle/archive/2.4.0.tar.gz : b8656dc08ab4af23d001a42b3f68510d15790df28d7d666d3f91e3fe9bf8e938
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python_test
