name       : pycodestyle
version    : 2.6.0
release    : 8
source     :
    - https://github.com/PyCQA/pycodestyle/archive/2.6.0.tar.gz : 08347fbc48cc92afd33117c1e8af9b99b292a4e5889f6b776f402e062fc39c97
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python3)
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
