name       : pycodestyle
version    : 2.8.0
release    : 12
source     :
    - https://github.com/PyCQA/pycodestyle/archive/refs/tags/2.8.0.tar.gz : 9116bd3686beaa22be34be1e5259fb9eecbf246a3991849d33ff6ab07d52f86e
homepage   : https://github.com/PyCQA/pycodestyle
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python3)
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
