name       : pycodestyle
version    : 2.10.0
release    : 14
source     :
    - https://github.com/PyCQA/pycodestyle/archive/refs/tags/2.10.0.tar.gz : a7306561f1ddf7bc00419b9f0d698d312a8eaa173b834e7c8e4ff32db5efd27f
homepage   : https://github.com/PyCQA/pycodestyle
license    : MIT
component  : programming.python
summary    : Python style guide checker
description: |
    pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
builddeps  :
    - pkgconfig(python3)
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
